### PR TITLE
issue-12-final-project-UI | Daniel Pham

### PR DESCRIPTION
**Pull request by dnypham**
Screen Shot 2022-02-11 at 11 48 50 AM
Screen Shot 2022-02-11 at 11 49 45 AM
Screen Shot 2022-02-11 at 11 47 25 AM
Screen Shot 2022-02-11 at 11 47 49 AM

### CODE REVIEW

**Comment by dnypham** [comment]
eventinerary-loading

**Comment by dnypham** [comment]
eventinerary-responsive

**Comment by dnypham** [comment]
eventinerary-menu

**Review by scbowler — APPROVED** [review]
Looks good! 👍

**Pull request merged**
